apiVersion: apps/v1
kind: Deployment
metadata:
  name: operators-orc
  labels:
    app: operators-orc
spec:
  replicas: 1
  template:
    metadata:
      name: operators-orc
      labels:
        app: operators-orc
    spec:
      serviceAccountName: operators-orc
      restartPolicy: Always
      containers:
        - name: operators-orc
          image: yurikrupnik/operators-orc:main
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: MONGO_URI
              value: "mongodb://host.docker.internal"
            - name: REDIS_URI
              value: "redis://localhost:6379"
#              valueFrom:
#                secretKeyRef:
#                  key: mongo-uri
#                  name: mongo-uri
  selector:
    matchLabels:
      app: operators-orc
