apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-actix
  labels:
    app: web-actix
spec:
  replicas: 1
  template:
    metadata:
      name: web-actix
      labels:
        app: web-actix
    spec:
      serviceAccountName: web-actix
      restartPolicy: Always
      containers:
        - name: web-actix
          image: yurikrupnik/web-actix:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
#          env:
#            - name: MONGO_URI
#              valueFrom:
#                secretKeyRef:
#                  key: mongo-uri
#                  name: mongo-uri
  selector:
    matchLabels:
      app: web-actix
