apiVersion: apps.kusionstack.io/v1alpha1
kind: CollaSet
metadata:
  name: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - image: wu8685/echo:1.3
          name: server
          command:
            - /server
          resources:
            limits:
              cpu: "0.1"
              ephemeral-storage: 100Mi
              memory: 100Mi
            requests:
              cpu: "0.1"
              ephemeral-storage: 100Mi
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-spec: slb.s1.small
    service.beta.kubernetes.io/backend-type: eni
  labels:
    kusionstack.io/control: "true"  # this label is required
  name: server
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: server
#  type: LoadBalancer