apiVersion: v1
kind: Service
metadata:
  name: operators-orc
  annotations:
    "prometheus.io/scrape": "true"
  labels:
    run: operators-orc
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: operators-orc
