apiVersion: v1
kind: Service
metadata:
  name: web-actix
  annotations:
    "prometheus.io/scrape": "true"
  labels:
    run: web-actix
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: web-actix
