
[workspace]
resolver = '2'
members = [
	'libs/models',
	'libs/services',
	'apps/web/actix',
	'apps/web/salvo',
	'apps/web/ntex',
	'apps/web/axum',
	'apps/operators/zerg',
	'apps/operators/protos',
	'libs/shared',
]

[profile.release]
opt-level = 'z'
codegen-units = 1
strip = true
lto = true
