[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.watch-test]
command = "cargo"
args = ["watch", "-q", "-c", "-N", "-x", "test -- --nocapture"]
#script_runner = "python3"
#script_extension = "py"
#script = '''
#print("Hello, World!")
#'''

[tasks.perl]
script_runner = "perl"
script_extension = "pl"
script = '''
print "Hello, World!\n";
'''

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.my-flow]
dependencies = [
  "format",
  "build",
  "test"
]
