# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  install-deps:
    cmds:
      - kind create cluster
      - sleep 15
      - timoni bundle apply -f manifests/podinfo.bundle.cue
