[package]
name = "manager_alina"
version = "0.1.0"
edition = "2021"


[dependencies]
rand = "0.9.0-alpha.1"
fake = { version = "2.9", features = ["derive"] }


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
